-- 조회
SELECT * FROM E_MEMBER;
SELECT * FROM E_MEMBER_AUTH;
SELECT * FROM E_ARTICLE;
SELECT * FROM E_ARTICLE_LIKE;
SELECT * FROM E_ARTICLE_HASHTAG;

-- 테이블 삭제
DROP TABLE E_MEMBER;
DROP TABLE E_MEMBER_AUTH;
DROP TABLE E_ARTICLE;
DROP TABLE E_ARTICLE_LIKE;
DROP TABLE E_ARTICLE_HASHTAG;

-- 시퀀스 삭제
DROP SEQUENCE E_MEMBER_SEQ;
DROP SEQUENCE E_MEMBER_AUTH_SEQ;
DROP SEQUENCE E_ARTICLE_SEQ;
DROP SEQUENCE E_ARTICLE_LIKE_SEQ;
DROP SEQUENCE E_ARTICLE_HASHTAG_SEQ;

SELECT E_MEMBER_SEQ.CURRVAL FROM dual;
SELECT * FROM user_sequences;

-- 멤버 테이블
CREATE TABLE E_MEMBER (
  MNO NUMBER,
  MID VARCHAR2(40) NOT NULL,
  MPASSWORD VARCHAR2(100) NOT NULL,
  MNICKNAME VARCHAR2(60) NOT NULL,
  MNAME VARCHAR2(40) NOT NULL,
  MBIRTH DATE NOT NULL,
  MGENDER VARCHAR2(3) NOT NULL,
  MEMAIL VARCHAR2(60),
  MPHONE VARCHAR2(40) NOT NULL,
  MZIP VARCHAR2(10),
  MADDR1 VARCHAR2(200),
  MADDR2 VARCHAR2(200),
  MVISITEDCOUNT NUMBER DEFAULT 0,
  MCOMMENTCOUNT NUMBER DEFAULT 0,
  MBOARDCOUNT NUMBER DEFAULT 0,
  MAUTHID VARCHAR2(3) DEFAULT '01' NOT NULL,
  MINSERTDATE DATE DEFAULT SYSDATE,
  MINSERTIP VARCHAR2(100) NOT NULL,
  MUPDATEDATE DATE,
  MUPDATEIP VARCHAR2(100),
  MUPDATEID VARCHAR2(40),
  MDELETEYN VARCHAR2(1) DEFAULT 'N',
  MDELETEDATE DATE,
  MDELETEIP VARCHAR2(100),
  MDELETEID VARCHAR2(40),
  PRIMARY KEY(MNO)
);

-- 멤버 시퀀스
CREATE SEQUENCE E_MEMBER_SEQ START WITH 1 INCREMENT BY 1;

-- 멤버권한 테이블
CREATE TABLE E_MEMBER_AUTH (
	MAUTHNO NUMBER,
    MAUTHID VARCHAR2(3) NOT NULL,
    MAUTHNAME VARCHAR2(20) NOT NULL,
	PRIMARY KEY(MAUTHNO)
);

-- 멤버권한 시퀀스
CREATE SEQUENCE E_MEMBER_AUTH_SEQ START WITH 1 INCREMENT BY 1;

-- 게시글 테이블
CREATE TABLE E_ARTICLE (
	ANO NUMBER,
    ATITLE VARCHAR2(200) NOT NULL,
	ACONTENT VARCHAR2(3000) NOT NULL,
	AWRITER VARCHAR2(40) NOT NULL,
	AVIEWCNT NUMBER DEFAULT 0,
	ACATEGORYNO NUMBER NOT NULL,
	ACATEGORYNOREF NUMBER,
	AINSERTDATE DATE DEFAULT SYSDATE,
	AINSERTIP VARCHAR2(100) NOT NULL,
	AINSERTID VARCHAR2(40) NOT NULL,
	AUPDATEDATE DATE,
	AUPDATEIP VARCHAR2(100),
	AUPDATEID VARCHAR2(40),
	ADELETEYN VARCHAR2(1) DEFAULT 'N',
	ADELETEDATE DATE,
	ADELETEIP VARCHAR2(100),
	ADELETEID VARCHAR2(40),
    PRIMARY KEY(ANO)
);

-- 콘텐츠 길이 확인
SELECT LENGTHB(ACONTENT) FROM E_ARTICLE;

-- 게시글 시퀀스
CREATE SEQUENCE E_ARTICLE_SEQ START WITH 1 INCREMENT BY 1;

-- 게시글 좋아요 테이블
CREATE TABLE E_ARTICLE_LIKE (
	LNO NUMBER,
    ANO NUMBER NOT NULL,
	MID VARCHAR2(40) NOT NULL,
    PRIMARY KEY(LNO)
);

-- 게시글 좋아요 시퀀스
CREATE SEQUENCE E_ARTICLE_LIKE_SEQ START WITH 1 INCREMENT BY 1;

-- 게시글 해쉬태그 테이블
CREATE TABLE E_ARTICLE_HASHTAG (
	HNO NUMBER,
	ANO NUMBER NOT NULL,
	HASHTAG_NAME VARCHAR2(60) NOT NULL,
	PRIMARY KEY(HNO)
);

-- 게시글 해쉬태그 시퀀스
CREATE SEQUENCE E_ARTICLE_HASHTAG_SEQ START WITH 1 INCREMENT BY 1;