/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-31 06:09:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.article;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class articleList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SpringWeb/sts_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ever/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1642396012685L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<title>articleList</title>\r\n");
      out.write("<script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("<style>\r\n");
      out.write("	table .ellipsis {\r\n");
      out.write("		position: relative;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.table .ellipsis span {\r\n");
      out.write("		overflow: hidden;\r\n");
      out.write("		white-space: nowrap;\r\n");
      out.write("		text-overflow: ellipsis;\r\n");
      out.write("		position: absolute;\r\n");
      out.write("		left: 9px;\r\n");
      out.write("		right: 9px;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	.ellipsis:before {\r\n");
      out.write("		content: '';\r\n");
      out.write("		display: inline-block;\r\n");
      out.write("	}\r\n");
      out.write("</style>\r\n");
      out.write("<script>\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		$(\"#writeBtn\").click(function() {\r\n");
      out.write("			location.href=\"/article/write\";\r\n");
      out.write("		});\r\n");
      out.write("	});\r\n");
      out.write("</script>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write(" <main id=\"main\" class=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"container pagetitle\" style=\"width:860px; margin:0 auto;\">\r\n");
      out.write("      <h1>전체 글 보기</h1>\r\n");
      out.write("    </div><!-- End Page Title -->\r\n");
      out.write("\r\n");
      out.write("	<div class=\"container\" style=\"width:860px; margin:0 auto;\">\r\n");
      out.write("		<table class=\"table table-sm bg-white\" style=\"border-collapse:inherit;\">\r\n");
      out.write("		  <div>\r\n");
      out.write("			  <span style=\"float:left; margin-top:7px;\">3,000,000개의 글</span>\r\n");
      out.write("			  <span style=\"float:right; margin-bottom:2px;\">\r\n");
      out.write("				<select class=\"form-select form-select-sm\" aria-label=\"Default select example\">\r\n");
      out.write("				  <option selected>5개씩</option>\r\n");
      out.write("				  <option value=\"1\">10개씩</option>\r\n");
      out.write("				  <option value=\"2\">15개씩</option>\r\n");
      out.write("				  <option value=\"3\">20개씩</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			  </span>\r\n");
      out.write("		  </div>\r\n");
      out.write("		  <div style=\"clear:both;\"></div>\r\n");
      out.write("		  <hr style=\"border:1px solid black;\">\r\n");
      out.write("		  <thead>\r\n");
      out.write("			<tr>\r\n");
      out.write("			  <th class=\"col-1\"></th>\r\n");
      out.write("			  <th class=\"col-7 text-center\">제목</th>\r\n");
      out.write("			  <th class=\"col-2\">작성자</th>\r\n");
      out.write("			  <th scope=\"col\">작성일</th>\r\n");
      out.write("			  <th class=\"col-1\">조회</th>\r\n");
      out.write("			</tr>\r\n");
      out.write("		  </thead>\r\n");
      out.write("		  <tbody>\r\n");
      out.write("			<tr>\r\n");
      out.write("			  <td class=\"ellipsis\" style=\"vertical-align: middle;\"><span><div class=\"badge badge-sm badge-success\" style=\"background:red;\">공지</div></span></th>\r\n");
      out.write("			  <td class=\"text-left ellipsis\"><span class=\"\">[내가 싼 똥] 핸님들은 뭔가 애착인형같은거 있나여ggggggggggggggggggggggggg</span></td>\r\n");
      out.write("			  <td class=\"ellipsis\"><span>김단향</span></td>\r\n");
      out.write("			  <td class=\"ellipsis\"><span>2019.09.30.</span></td>\r\n");
      out.write("			  <td class=\"ellipsis\"><span>2.2만</span></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("			  <td class=\"ellipsis\" style=\"font-size:12px; vertical-align: middle;\"><span>유저게시판</span></th>\r\n");
      out.write("			  <td class=\"text-left ellipsis\"><span class=\"\">[내가 싼 똥] 핸님들은 뭔가 애착인형같은거 있나여ggggggggggggggggggggggggg</span></td>\r\n");
      out.write("			  <td class=\"ellipsis\"><span>김단향</span></td>\r\n");
      out.write("			  <td class=\"ellipsis\"><span>2019.09.30.</span></td>\r\n");
      out.write("			  <td class=\"ellipsis\"><span>2.2만</span></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("			<tr>\r\n");
      out.write("			  <td class=\"ellipsis\"><span><div class=\"badge badge-sm badge-success\" style=\"background:red;\">공지</div></span></th>\r\n");
      out.write("			  <td class=\"text-left ellipsis\"><span class=\"\">[내가 싼 똥] 핸님들은 뭔가 애착인형같은거 있나여ggggggggggggggggggggggggg</span></td>\r\n");
      out.write("			  <td class=\"ellipsis\"><span>김단향</span></td>\r\n");
      out.write("			  <td class=\"ellipsis\"><span>2019.09.30.</span></td>\r\n");
      out.write("			  <td class=\"ellipsis\"><span>2.2만</span></td>\r\n");
      out.write("			</tr>\r\n");
      out.write("		  </tbody>\r\n");
      out.write("		</table>\r\n");
      out.write("\r\n");
      out.write("		<nav aria-label=\"Page navigation example \">\r\n");
      out.write("		  <ul class=\"pagination pagination-sm justify-content-center\">\r\n");
      out.write("			<li class=\"page-item ms-1 me-1\">\r\n");
      out.write("			  <a class=\"page-link\" href=\"#\" aria-label=\"Previous\">\r\n");
      out.write("				<span aria-hidden=\"true\">&laquo; 이전</span>\r\n");
      out.write("			  </a>\r\n");
      out.write("			</li>\r\n");
      out.write("			<li class=\"page-item ms-1 me-1\"><a class=\"page-link\" href=\"#\">1</a></li>\r\n");
      out.write("			<li class=\"page-item ms-1 me-1\"><a class=\"page-link\" href=\"#\">2</a></li>\r\n");
      out.write("			<li class=\"page-item ms-1 me-1\"><a class=\"page-link\" href=\"#\">3</a></li>\r\n");
      out.write("			<li class=\"page-item ms-1 me-1\">\r\n");
      out.write("			  <a class=\"page-link\" href=\"#\" aria-label=\"Next\">\r\n");
      out.write("				<span aria-hidden=\"true\">다음 &raquo;</span>\r\n");
      out.write("			  </a>\r\n");
      out.write("			</li>\r\n");
      out.write("		  </ul>\r\n");
      out.write("		</nav>\r\n");
      out.write("\r\n");
      out.write("		<div class=\"container\">\r\n");
      out.write("			<div style=\"width:100%; text-align:center;\">\r\n");
      out.write("			  <div style=\"display:inline-block\">\r\n");
      out.write("				<select class=\"form-select form-select-sm\">\r\n");
      out.write("				  <option selected>전체기간</option>\r\n");
      out.write("				  <option value=\"1\">1일</option>\r\n");
      out.write("				  <option value=\"2\">1주</option>\r\n");
      out.write("				  <option value=\"3\">1개월</option>\r\n");
      out.write("				  <option value=\"3\">6개월</option>\r\n");
      out.write("				  <option value=\"3\">1년</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			  </div>\r\n");
      out.write("\r\n");
      out.write("			  <div style=\"display:inline-block\">\r\n");
      out.write("				<select class=\"form-select form-select-sm\">\r\n");
      out.write("				  <option selected>게시글</option>\r\n");
      out.write("				  <option value=\"1\">제목만</option>\r\n");
      out.write("				  <option value=\"2\">글작성자</option>\r\n");
      out.write("				  <option value=\"3\">댓글내용</option>\r\n");
      out.write("				  <option value=\"3\">댓글작성자</option>\r\n");
      out.write("				</select>\r\n");
      out.write("			  </div>\r\n");
      out.write("\r\n");
      out.write("			  <div style=\"display:inline-block\">\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("				  <input type=\"text\" class=\"form-control form-control-sm\" placeholder=\"검색어를 입력해주세요\" aria-label=\"Recipient's username\" aria-describedby=\"button-addon2\">\r\n");
      out.write("				  <button class=\"btn btn-success btn-sm\" type=\"button\" id=\"button-addon2\">검색</button>\r\n");
      out.write("				</div>\r\n");
      out.write("			  </div>\r\n");
      out.write("			</div>\r\n");
      out.write("		<div>\r\n");
      out.write("		\r\n");
      out.write("		<div id=\"writeBtn\" class=\"btn btn-success btn-sm\">글쓰기</div>\r\n");
      out.write("\r\n");
      out.write("	</div>\r\n");
      out.write("\r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fimport_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/article/articleList.jsp(39,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/header");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/views/article/articleList.jsp(40,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/sidebar");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f2 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f2_reused = false;
    try {
      _jspx_th_c_005fimport_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f2.setParent(null);
      // /WEB-INF/views/article/articleList.jsp(153,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f2.setUrl("/footer");
      int[] _jspx_push_body_count_c_005fimport_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f2 = _jspx_th_c_005fimport_005f2.doStartTag();
        if (_jspx_th_c_005fimport_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f2);
      _jspx_th_c_005fimport_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f2_reused);
    }
    return false;
  }
}
