/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-02-10 05:48:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SpringWeb/sts_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ever/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1642396012685L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, false, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>Pages / Login - NiceAdmin Bootstrap Template</title>\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"/assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.gstatic.com\" rel=\"preconnect\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("  <link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.8.2/css/all.min.css\"/>\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"/assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/quill/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/quill/quill.bubble.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/simple-datatables/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"/assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"/assets/vendor/apexcharts/apexcharts.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/chart.js/chart.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/echarts/echarts.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/quill/quill.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/simple-datatables/simple-datatables.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/tinymce/tinymce.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"/assets/js/main.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: NiceAdmin - v2.2.1\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("  <style>\r\n");
      out.write("    .find-info {\r\n");
      out.write("	    list-style-type: none;\r\n");
      out.write("	    margin: 0;\r\n");
      out.write("	    padding: 0;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .find-info li {\r\n");
      out.write("	    margin: 0 0 0 0;\r\n");
      out.write("	    padding: 0 0 0 0;\r\n");
      out.write("	    border: 0;\r\n");
      out.write("	    float: left;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .find-info li:after {\r\n");
      out.write("	    content: '｜';\r\n");
      out.write("	    padding-left: 5px;\r\n");
      out.write("	    padding-right: 7px;\r\n");
      out.write("	    color: rgb(220 220 220);\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .find-info li:last-child:after {\r\n");
      out.write("	    content: \"\";\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #yourUsername {\r\n");
      out.write("		padding: 12px;  \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #yourPassword {\r\n");
      out.write("		padding: 12px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #loginBtn {\r\n");
      out.write("		padding: 12px;\r\n");
      out.write("		font-size: 23px;\r\n");
      out.write("		font-weight: 400;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .your-input {\r\n");
      out.write("		border: 1px solid #ced4da;\r\n");
      out.write("		border-left:0px;      \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .your-input:focus {\r\n");
      out.write("		box-shadow: none;\r\n");
      out.write("		outline: none;\r\n");
      out.write("		border: 1px solid #ced4da;\r\n");
      out.write("		border-left:0px;     \r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .input-group-text {\r\n");
      out.write("		border-right:0px; \r\n");
      out.write("		background:white;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .link-text {\r\n");
      out.write("    	text-decoration:none; \r\n");
      out.write("    	color:#888;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("  </style>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <main>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("      <section class=\"section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row justify-content-center\">\r\n");
      out.write("            <div class=\"col-xl-4 col-lg-5 col-md-7 col-sm-10 d-flex flex-column align-items-center justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("              <div class=\"d-flex justify-content-center py-4\">\r\n");
      out.write("                <a href=\"index.html\" class=\"logo d-flex align-items-center w-auto\">\r\n");
      out.write("                  <img src=\"assets/img/logo.png\" alt=\"\">\r\n");
      out.write("                  <span class=\"d-none d-lg-block\">NiceAdmin</span>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div><!-- End Logo -->\r\n");
      out.write("\r\n");
      out.write("              <div class=\"card mb-3\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-body\" style=\"margin: 80px 0 30px 0;\">\r\n");
      out.write("\r\n");
      out.write("                  <form name=\"loginForm\" action=\"/member/login\" method=\"post\" class=\"row g-3 needs-validation\" novalidate>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <div class=\"input-group has-validation\">\r\n");
      out.write("                        <span class=\"input-group-text\" id=\"basic-addon2\">\r\n");
      out.write("                          <i class=\"fas fa-user\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <input type=\"text\" name=\"mid\" class=\"form-control your-input\" \r\n");
      out.write("                               placeholder=\"아이디\" id=\"yourUsername\" required>\r\n");
      out.write("                        <div class=\"invalid-feedback\">Please enter your username.</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\" style=\"margin-top:1px;\">\r\n");
      out.write("                      <div class=\"input-group has-validation\">\r\n");
      out.write("                        <span class=\"input-group-text\" id=\"basic-addon2\">\r\n");
      out.write("                          <i class=\"fas fa-unlock\"></i>\r\n");
      out.write("                        </span>\r\n");
      out.write("                        <input type=\"password\" name=\"mpassword\" class=\"form-control your-input\" \r\n");
      out.write("                              placeholder=\"비밀번호\" id=\"yourPassword\" required>\r\n");
      out.write("                        <div class=\"invalid-feedback\">Please enter your password!</div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <div class=\"form-check\">\r\n");
      out.write("                        <input class=\"form-check-input\" type=\"checkbox\" name=\"remember\" value=\"true\" id=\"rememberMe\">\r\n");
      out.write("                        <label class=\"form-check-label\" for=\"rememberMe\">로그인 상태 유지</label>\r\n");
      out.write("                      </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    \r\n");
      out.write("                    ");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <button id=\"loginBtn\" class=\"btn btn-primary w-100\" type=\"submit\">로그인</button>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("              <div class=\"credits\">\r\n");
      out.write("                <ul class=\"find-info\">\r\n");
      out.write("                  <li>\r\n");
      out.write("                  	<a class=\"link-text\" href=\"/member/register\">비밀번호 찾기</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                  	<a class=\"link-text\" href=\"/member/register\">아이디 찾기</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                  <li>\r\n");
      out.write("                  	<a class=\"link-text\" href=\"/member/register\">회원가입</a>\r\n");
      out.write("                  </li>\r\n");
      out.write("                </ul>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("      </section>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#\" class=\"back-to-top d-flex align-items-center justify-content-center\"><i class=\"bi bi-arrow-up-short\"></i></a>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/member/login.jsp(172,20) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${msg == false}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    	<p style=\"color:red;\">로그인 실패! 아이디와 비밀번호 확인해주세요!</p>\r\n");
          out.write("                    ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }
}
