/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-02-21 15:14:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.member;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class register_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SpringWeb/sts_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ever/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1642396012685L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"en\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>Pages / Register - NiceAdmin Bootstrap Template</title>\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Favicons -->\r\n");
      out.write("  <link href=\"/assets/img/favicon.png\" rel=\"icon\">\r\n");
      out.write("  <link href=\"/assets/img/apple-touch-icon.png\" rel=\"apple-touch-icon\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Google Fonts -->\r\n");
      out.write("  <link href=\"https://fonts.gstatic.com\" rel=\"preconnect\">\r\n");
      out.write("  <link href=\"https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor CSS Files -->\r\n");
      out.write("  <link href=\"/assets/vendor/bootstrap/css/bootstrap.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/bootstrap-icons/bootstrap-icons.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/boxicons/css/boxicons.min.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/quill/quill.snow.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/quill/quill.bubble.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/remixicon/remixicon.css\" rel=\"stylesheet\">\r\n");
      out.write("  <link href=\"/assets/vendor/simple-datatables/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main CSS File -->\r\n");
      out.write("  <link href=\"/assets/css/style.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("  <!-- Vendor JS Files -->\r\n");
      out.write("  <script src=\"/assets/vendor/apexcharts/apexcharts.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/bootstrap/js/bootstrap.bundle.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/chart.js/chart.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/echarts/echarts.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/quill/quill.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/simple-datatables/simple-datatables.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/tinymce/tinymce.min.js\"></script>\r\n");
      out.write("  <script src=\"/assets/vendor/php-email-form/validate.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <!-- Template Main JS File -->\r\n");
      out.write("  <script src=\"/assets/js/main.js\"></script>\r\n");
      out.write("  <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("  <style>\r\n");
      out.write("    .your-label {\r\n");
      out.write("    	font-weight: bold;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .your-input {\r\n");
      out.write("    	padding: 8px;\r\n");
      out.write("    	border-radius: 0px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    .your-input:focus {\r\n");
      out.write("    	box-shadow: none;\r\n");
      out.write("    	outline: none;\r\n");
      out.write("    	border: 1px solid #ced4da;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #basic-addon2 {\r\n");
      out.write("    	border-left:0px; \r\n");
      out.write("    	background:white;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #yourId {\r\n");
      out.write("    	border-right:0px;\r\n");
      out.write("    }\r\n");
      out.write("\r\n");
      out.write("    #yourId:focus {\r\n");
      out.write("    	border-right:0px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .btn-submit {\r\n");
      out.write("    	padding: 12px;\r\n");
      out.write("    }\r\n");
      out.write("    \r\n");
      out.write("    .fs-13 {\r\n");
      out.write("    	font-size: 13px;\r\n");
      out.write("    }\r\n");
      out.write("  </style>\r\n");
      out.write("  \r\n");
      out.write("  <script type=\"text/javascript\">\r\n");
      out.write("  	$(document).ready(function() {\r\n");
      out.write("		mbirthFunc();\r\n");
      out.write("		\r\n");
      out.write("		let idValid = false;\r\n");
      out.write("		let passwordValid = false;\r\n");
      out.write("		let rePasswordValid = false;\r\n");
      out.write("		let nameValid = false;\r\n");
      out.write("		let nicknameValid = false;\r\n");
      out.write("		let birthValid = false;\r\n");
      out.write("		let genderValid = false;\r\n");
      out.write("		let emailValid = false;\r\n");
      out.write("		let phoneValid = false;\r\n");
      out.write("		let phoneConfirmValid = false;\r\n");
      out.write("		\r\n");
      out.write("		let code2 = \"\";\r\n");
      out.write("		\r\n");
      out.write("	  	$(\"#phoneBtn\").on(\"click\", function() {\r\n");
      out.write("			let phone = $(\"#yourPhone\").val();\r\n");
      out.write("\r\n");
      out.write("			if(phone == \"\") {\r\n");
      out.write("	  			$(\"#yourPhoneMsg\").text(\"필수 정보입니다.\");\r\n");
      out.write("	  			$(\"#yourPhoneMsg\").css(\"color\", \"red\");\r\n");
      out.write("	  			return false;\r\n");
      out.write("	  		}\r\n");
      out.write("\r\n");
      out.write("	  		alert(\"인증번호를 발송하였습니다.\\n휴대폰에서 인증번호를 확인해주세요.\");\r\n");
      out.write("			console.log(\"폰번호 : \" + phone);\r\n");
      out.write("			\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type: \"get\",\r\n");
      out.write("				data: {\r\n");
      out.write("					phone: phone\r\n");
      out.write("				},\r\n");
      out.write("				url:\"/phoneCheck\",\r\n");
      out.write("				cache: false,\r\n");
      out.write("				success: function(data) {\r\n");
      out.write("					if(data == \"error\") {\r\n");
      out.write("						alert(\"휴대폰 번호가 올바르지 않습니다.\\n번호만 입력해주세요.\");\r\n");
      out.write("						$(\"#yourPhoneConfirmMsg\").text(\"유효한 번호를 입력해주세요.\");\r\n");
      out.write("						$(\"#yourPhoneConfirmMsg\").css(\"color\", \"red\");\r\n");
      out.write("						$(\"#yourPhone\").attr(\"autofocus\", true);\r\n");
      out.write("					} else {\r\n");
      out.write("						$(\"#yourPhoneConfirm\").attr(\"disabled\", false);\r\n");
      out.write("						$(\"#yourPhoneConfirmMsg\").text(\"인증번호를 입력한 뒤 본인인증을 눌러주세요.\");\r\n");
      out.write("						$(\"#yourPhoneConfirmMsg\").css(\"color\", \"#08a600\");\r\n");
      out.write("						$(\"#yourPhone\").attr(\"readonly\", true);\r\n");
      out.write("						code2 = data;\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("	  	});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#yourPhoneConfirm\").on(\"input\", function() {\r\n");
      out.write("			console.log($(\"#yourPhoneConfirm\").val() == code2);\r\n");
      out.write("			console.log($(\"#yourPhoneConfirm\").val());\r\n");
      out.write("			console.log(code2);\r\n");
      out.write("			if($(\"#yourPhoneConfirm\").val() == code2) {\r\n");
      out.write("				$(\"#yourPhoneConfirmMsg\").text(\"인증번호가 일치합니다.\");\r\n");
      out.write("				$(\"#yourPhoneConfirmMsg\").css(\"color\", \"#08a600\");\r\n");
      out.write("				$(\"#yourPhoneConfirm\").attr(\"disabled\", true);\r\n");
      out.write("				phoneConfirmValid = true;\r\n");
      out.write("				return;\r\n");
      out.write("			} else {\r\n");
      out.write("				$(\"#yourPhoneConfirmMsg\").text(\"인증번호가 일치하지 않습니다. 확인해주시기 바랍니다.\");\r\n");
      out.write("				$(\"#yourPhoneConfirmMsg\").css(\"color\", \"red\");\r\n");
      out.write("				$(this).attr(\"autofocus\", true);\r\n");
      out.write("				phoneConfirmValid = false;\r\n");
      out.write("				return;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			phoneConfirmValid = false;\r\n");
      out.write("		})\r\n");
      out.write("		\r\n");
      out.write("		$(\"#yourId\").on(\"blur\", function() {\r\n");
      out.write("			const yourIdVal = $(\"#yourId\").val();\r\n");
      out.write("			idValid = idCheck(yourIdVal);\r\n");
      out.write("			\r\n");
      out.write("			scrollChange($(\"#yourId\"), idValid);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#yourPassword\").on(\"blur\", function() {\r\n");
      out.write("			const yourPasswordVal = $(\"#yourPassword\").val();\r\n");
      out.write("			passwordValid = passwordCheck(yourPasswordVal);\r\n");
      out.write("			\r\n");
      out.write("			scrollChange($(\"#yourPassword\"), passwordValid);\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#yourRePassword\").on(\"blur\", function() {\r\n");
      out.write("			const yourRePasswordVal = $(\"#yourRePassword\").val();\r\n");
      out.write("			const yourPasswordVal = $(\"#yourPassword\").val();\r\n");
      out.write("			rePasswordValid = passwordReCheck(yourRePasswordVal, yourPasswordVal);\r\n");
      out.write("			\r\n");
      out.write("			scrollChange($(\"#yourRePassword\"), rePasswordValid);		\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#yourName\").on(\"blur\", function() {\r\n");
      out.write("			const yourNameVal = $(\"#yourName\").val();\r\n");
      out.write("			nameValid = nameCheck(yourNameVal);\r\n");
      out.write("			\r\n");
      out.write("			scrollChange($(\"#yourName\"), nameValid);	\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#yourNickname\").on(\"blur\", function() {\r\n");
      out.write("			const yourNicknameVal = $(\"#yourNickname\").val();\r\n");
      out.write("			nicknameValid = nicknameCheck(yourNicknameVal);\r\n");
      out.write("			\r\n");
      out.write("			scrollChange($(\"#yourNickname\"), nicknameValid);	\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#yourBirth\").on(\"blur\", function() {\r\n");
      out.write("			const yourBirthVal = $(\"#yourBirth\").val();\r\n");
      out.write("			birthValid = birthCheck(yourBirthVal);\r\n");
      out.write("		\r\n");
      out.write("			scrollChange($(\"#yourBirth\"), birthValid);		\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		$(\"#yourGender\").on(\"blur\", function() {\r\n");
      out.write("			const yourGenderVal = $(\"#yourGender\").val();\r\n");
      out.write("			genderValid = genderCheck(yourGenderVal);\r\n");
      out.write("			\r\n");
      out.write("			scrollChange($(\"#yourGender\"), genderValid);	\r\n");
      out.write("		});\r\n");
      out.write("\r\n");
      out.write("		$(\"#yourEmail\").on(\"blur\", function() {\r\n");
      out.write("			const yourEmailVal = $(\"#yourEmail\").val();\r\n");
      out.write("			emailValid = emailCheck(yourEmailVal);\r\n");
      out.write("			\r\n");
      out.write("			scrollChange($(\"#yourEmail\"), emailValid);	\r\n");
      out.write("		});		\r\n");
      out.write("\r\n");
      out.write("		/*\r\n");
      out.write("		$(\"#yourPhone\").on(\"blur\", function() {\r\n");
      out.write("			const yourPhoneVal = $(\"#yourPhone\").val();\r\n");
      out.write("			phoneValid = phoneCheck(yourPhoneVal);		\r\n");
      out.write("			\r\n");
      out.write("			scrollChange($(\"#yourPhone\"), phoneValid);	\r\n");
      out.write("		});\r\n");
      out.write("		*/\r\n");
      out.write("		\r\n");
      out.write("		$(\"#btn-submit\").on(\"click\", function() {\r\n");
      out.write("			if(!idValid) {\r\n");
      out.write("				// 아이디 체크\r\n");
      out.write("				console.log(\"idValid\");\r\n");
      out.write("				const yourIdVal = $(\"#yourId\").val();\r\n");
      out.write("				idValid = idCheck(yourIdVal);\r\n");
      out.write("				scrollChange($(\"#yourId\"), idValid);	\r\n");
      out.write("				return;\r\n");
      out.write("			} else if(!passwordValid) {\r\n");
      out.write("				// 비밀번호 체크\r\n");
      out.write("				console.log(\"passwordValid\");\r\n");
      out.write("				const yourPasswordVal = $(\"#yourPassword\").val();\r\n");
      out.write("				passwordValid = passwordCheck(yourPasswordVal);\r\n");
      out.write("				scrollChange($(\"#yourPassword\"), passwordValid);\r\n");
      out.write("				return;\r\n");
      out.write("			} else if(!rePasswordValid) {	\r\n");
      out.write("				// 비밀번호 재확인 체크\r\n");
      out.write("				console.log(\"rePasswordValid\");\r\n");
      out.write("				const yourPasswordVal = $(\"#yourPassword\").val();\r\n");
      out.write("				const yourRePasswordVal = $(\"#yourRePassword\").val();\r\n");
      out.write("				rePasswordValid = passwordReCheck(yourRePasswordVal, yourPasswordVal);\r\n");
      out.write("				scrollChange($(\"#yourRePassword\"), rePasswordValid);	\r\n");
      out.write("				return;\r\n");
      out.write("			} else if(!nameValid) {\r\n");
      out.write("				// 이름 체크\r\n");
      out.write("				console.log(\"nameValid\");\r\n");
      out.write("				const yourNameVal = $(\"#yourName\").val();\r\n");
      out.write("				nameValid = nameCheck(yourNameVal);\r\n");
      out.write("				scrollChange($(\"#yourName\"), nameValid);\r\n");
      out.write("				return;\r\n");
      out.write("			} else if(!nicknameValid) {\r\n");
      out.write("				// 별명 체크\r\n");
      out.write("				console.log(\"nicknameValid\");\r\n");
      out.write("				const yourNicknameVal = $(\"#yourNickname\").val();\r\n");
      out.write("				nicknameValid = nicknameCheck(yourNicknameVal);\r\n");
      out.write("				scrollChange($(\"#yourNickname\"), nicknameValid);\r\n");
      out.write("				return;\r\n");
      out.write("			} else if(!birthValid) {\r\n");
      out.write("				// 생일 체크\r\n");
      out.write("				console.log(\"birthValid\");\r\n");
      out.write("				const yourBirthVal = $(\"#yourBirth\").val();\r\n");
      out.write("				birthValid = birthCheck(yourBirthVal);\r\n");
      out.write("				scrollChange($(\"#yourBirth\"), birthValid);	\r\n");
      out.write("				return;\r\n");
      out.write("			} else if(!genderValid) {\r\n");
      out.write("				// 성별 체크\r\n");
      out.write("				console.log(\"genderValid\");\r\n");
      out.write("				const yourGenderVal = $(\"#yourGender\").val();\r\n");
      out.write("				genderValid = genderCheck(yourGenderVal);\r\n");
      out.write("				scrollChange($(\"#yourGender\"), genderValid);\r\n");
      out.write("				return;\r\n");
      out.write("			} else if(!emailValid) {\r\n");
      out.write("				// 이메일 체크\r\n");
      out.write("				console.log(\"emailValid\");\r\n");
      out.write("				const yourEmailVal = $(\"#yourEmail\").val();\r\n");
      out.write("				emailValid = emailCheck(yourEmailVal);\r\n");
      out.write("				scrollChange($(\"#yourEmail\"), emailValid);	\r\n");
      out.write("				return;\r\n");
      out.write("			} else if(!phoneConfirmValid) {\r\n");
      out.write("				// 전화번호 체크\r\n");
      out.write("				if($(\"#yourPhone\").val == \"\") {\r\n");
      out.write("					$(\"#yourPhoneMsg\").text(\"필수 수정입니다.\");\r\n");
      out.write("					$(\"#yourPhoneMsg\").css(\"color\", \"red\");\r\n");
      out.write("				}\r\n");
      out.write("				\r\n");
      out.write("				console.log(\"z : \" + phoneConfirmValid);\r\n");
      out.write("				\r\n");
      out.write("				$(\"#yourPhoneConfirmMsg\").text(\"인증번호가 일치하지 않습니다. 확인해주시기 바랍니다.\");\r\n");
      out.write("				$(\"#yourPhoneConfirmMsg\").css(\"color\", \"red\");\r\n");
      out.write("				\r\n");
      out.write("				scrollChange($(\"#yourPhone\"), false);\r\n");
      out.write("				return;\r\n");
      out.write("			} else {\r\n");
      out.write("				const registerForm = $(\"#registerForm\");\r\n");
      out.write("				registerForm.attr(\"action\", \"/member/register\");\r\n");
      out.write("				registerForm.attr(\"method\", \"post\");\r\n");
      out.write("				registerForm.submit();\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("  	});\r\n");
      out.write("  	\r\n");
      out.write("  	function scrollChange(tag, valid) {		\r\n");
      out.write("		if(!valid) {\r\n");
      out.write("			let offset = tag.offset();\r\n");
      out.write("			let winH = $(window).height();\r\n");
      out.write("			$(\"html\").animate({scrollTop: (offset.top - winH/2)}, 200);\r\n");
      out.write("		}\r\n");
      out.write("  	}\r\n");
      out.write("  	\r\n");
      out.write("  	/*\r\n");
      out.write("  	function phoneCheck(val) {\r\n");
      out.write("  		if(val == \"\") {\r\n");
      out.write("  			$(\"#yourPhoneMsg\").text(\"필수 정보입니다.\");\r\n");
      out.write("  			$(\"#yourPhoneMsg\").css(\"color\", \"red\");\r\n");
      out.write("  			return false;\r\n");
      out.write("  		}\r\n");
      out.write("  		\r\n");
      out.write("  		return true;\r\n");
      out.write("  	}\r\n");
      out.write("  	*/\r\n");
      out.write("  	\r\n");
      out.write("  	function emailCheck(val) {\r\n");
      out.write("  		const regExp = /^([a-z0-9_\\.-]+)@([\\da-z\\.-]+)\\.([a-z\\.]{2,6})$/;\r\n");
      out.write("  		\r\n");
      out.write("  		if(val == \"\") {\r\n");
      out.write("  			$(\"#yourEmailMsg\").text(\"\");\r\n");
      out.write("  			return true;\r\n");
      out.write("  		}\r\n");
      out.write("  		\r\n");
      out.write("		if(!regExp.test(val)) {\r\n");
      out.write("			$(\"#yourEmailMsg\").text(\"이메일 주소를 다시 확인해주세요.\");\r\n");
      out.write("			$(\"#yourEmailMsg\").css(\"color\", \"red\");\r\n");
      out.write("			return false;				\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$(\"#yourEmailMsg\").text(\"\");\r\n");
      out.write("		return true;		\r\n");
      out.write("  	}\r\n");
      out.write("  	\r\n");
      out.write("  	function genderCheck(val) {\r\n");
      out.write("  		if(val == \"00\") {\r\n");
      out.write("			$(\"#yourGenderMsg\").text(\"필수 정보입니다.\");\r\n");
      out.write("			$(\"#yourGenderMsg\").css(\"color\", \"red\");\r\n");
      out.write("			return false; 	  			\r\n");
      out.write("  		}\r\n");
      out.write("  		\r\n");
      out.write("		$(\"#yourGenderMsg\").text(\"\");\r\n");
      out.write("		return true;\r\n");
      out.write("  	}\r\n");
      out.write("  	\r\n");
      out.write("  	function birthCheck(val) {\r\n");
      out.write("  		if(val == \"\") {\r\n");
      out.write("			$(\"#yourBirthMsg\").text(\"필수 정보입니다.\");\r\n");
      out.write("			$(\"#yourBirthMsg\").css(\"color\", \"red\");\r\n");
      out.write("			return false; 	  			\r\n");
      out.write("  		}\r\n");
      out.write("  		\r\n");
      out.write("		$(\"#yourBirthMsg\").text(\"\");\r\n");
      out.write("		return true;  		\r\n");
      out.write("  	}\r\n");
      out.write("  	\r\n");
      out.write("  	function nicknameCheck(val) {\r\n");
      out.write("  		const regExp = /^[a-zA-Z0-9가-힣][a-zA-Z0-9가-힣]{1,19}$/g;\r\n");
      out.write("  		let nicknameReturn = false;\r\n");
      out.write("  		\r\n");
      out.write("  		if(val == \"\") {\r\n");
      out.write("			$(\"#yourNicknameMsg\").text(\"필수 정보입니다.\");\r\n");
      out.write("			$(\"#yourNicknameMsg\").css(\"color\", \"red\");\r\n");
      out.write("			return false; 	  			\r\n");
      out.write("  		}\r\n");
      out.write("  		\r\n");
      out.write("		if(!regExp.test(val)) {\r\n");
      out.write("			$(\"#yourNicknameMsg\").text(\"2~20자의 영문 대 소문자 한글, 숫자만 사용 가능합니다.\");\r\n");
      out.write("			$(\"#yourNicknameMsg\").css(\"color\", \"red\");\r\n");
      out.write("			return false;				\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: \"/member/nicknameCheck\",\r\n");
      out.write("			method: \"get\",\r\n");
      out.write("			async: false,\r\n");
      out.write("			data: {\r\n");
      out.write("				mnickname : val\r\n");
      out.write("			},\r\n");
      out.write("			success: function(result) {\r\n");
      out.write("				if(result) {\r\n");
      out.write("					$(\"#yourNicknameMsg\").text(\"사용 가능한 별명입니다.\");\r\n");
      out.write("					$(\"#yourNicknameMsg\").css(\"color\", \"#08a600\");\r\n");
      out.write("					nicknameReturn = true;\r\n");
      out.write("				} else {	\r\n");
      out.write("					$(\"#yourNicknameMsg\").text(\"이미 사용중입니다. 다른 별명을 입력해주세요.\");\r\n");
      out.write("					$(\"#yourNicknameMsg\").css(\"color\", \"red\");\r\n");
      out.write("					nicknameReturn = false;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		return nicknameReturn;\r\n");
      out.write("  	}\r\n");
      out.write("  	\r\n");
      out.write("  	function nameCheck(val) {\r\n");
      out.write("  		const regExp = /^[a-zA-Z0-9가-힣][a-zA-Z0-9가-힣]{0,39}$/g;\r\n");
      out.write("  		\r\n");
      out.write("  		if(val == \"\") {\r\n");
      out.write("			$(\"#yourNameMsg\").text(\"필수 정보입니다.\");\r\n");
      out.write("			$(\"#yourNameMsg\").css(\"color\", \"red\");\r\n");
      out.write("			return false; 	  			\r\n");
      out.write("  		}\r\n");
      out.write("  		\r\n");
      out.write("		if(!regExp.test(val)) {\r\n");
      out.write("			console.log(regExp.test(val));\r\n");
      out.write("			$(\"#yourNameMsg\").text(\"한글과 영문 대 소문자를 사용하세요. (특수기호, 공백 사용 불가)\");\r\n");
      out.write("			$(\"#yourNameMsg\").css(\"color\", \"red\");\r\n");
      out.write("			return false;				\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$(\"#yourNameMsg\").text(\"\");\r\n");
      out.write("		return true;  		\r\n");
      out.write("  	}\r\n");
      out.write("  	\r\n");
      out.write("  	function passwordReCheck(yourPasswordVal, yourRePasswordVal) {\r\n");
      out.write("  		if(yourRePasswordVal == \"\") {\r\n");
      out.write("			$(\"#yourRePasswordMsg\").text(\"필수 정보입니다.\");\r\n");
      out.write("			$(\"#yourRePasswordMsg\").css(\"color\", \"red\");\r\n");
      out.write("			return false; 			\r\n");
      out.write("  		}\r\n");
      out.write("  		\r\n");
      out.write("  		if(yourPasswordVal != yourRePasswordVal) {\r\n");
      out.write("			$(\"#yourRePasswordMsg\").text(\"비밀번호가 일치하지 않습니다.\");\r\n");
      out.write("			$(\"#yourRePasswordMsg\").css(\"color\", \"red\");\r\n");
      out.write("			return false; 			 			\r\n");
      out.write("  		}\r\n");
      out.write("  		\r\n");
      out.write("		$(\"#yourRePasswordMsg\").text(\"\");\r\n");
      out.write("		return true;\r\n");
      out.write("  	}\r\n");
      out.write("  	\r\n");
      out.write("  	\r\n");
      out.write("  	function passwordCheck(val) {\r\n");
      out.write("  		const regExp = /^[a-zA-Z0-9\\{\\}\\[\\]\\/?.,;:|\\)*~`!^\\-_+<>@#$%&\\\\\\=\\(\\'\\\"]{8,16}$/g;\r\n");
      out.write("		//const regExp = /(?=.*[a-zA-Z0-9])(?=.*?[#?!@$%^&*-]).{8,16}/;\r\n");
      out.write("		\r\n");
      out.write("		if(val == \"\") {\r\n");
      out.write("			$(\"#yourPasswordMsg\").text(\"필수 정보입니다.\");\r\n");
      out.write("			$(\"#yourPasswordMsg\").css(\"color\", \"red\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(!regExp.test(val)) {\r\n");
      out.write("			console.log(regExp.test(val));\r\n");
      out.write("			$(\"#yourPasswordMsg\").text(\"8~16자 영문 대 소문자, 숫자, 특수문자를 사용하세요\");\r\n");
      out.write("			$(\"#yourPasswordMsg\").css(\"color\", \"red\");\r\n");
      out.write("			return false;				\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$(\"#yourPasswordMsg\").text(\"\");\r\n");
      out.write("		return true;\r\n");
      out.write("  	}  	\r\n");
      out.write("  	\r\n");
      out.write("  	function idCheck(val) {\r\n");
      out.write("		const regExp = /^[a-zA-Z0-9][a-zA-Z0-9-_]{4,19}$/g;\r\n");
      out.write("		let idReturn = false;\r\n");
      out.write("		\r\n");
      out.write("		if(val == \"\") {\r\n");
      out.write("			$(\"#yourIdMsg\").text(\"필수 정보입니다.\");\r\n");
      out.write("			$(\"#yourIdMsg\").css(\"color\", \"red\");\r\n");
      out.write("			return false;\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		if(!regExp.test(val)) {\r\n");
      out.write("			console.log(regExp.test(val));\r\n");
      out.write("			$(\"#yourIdMsg\").text(\"5~20자의 영문 대 소문자, 숫자와 특수기호(_),(-)만 사용 가능합니다.\");\r\n");
      out.write("			$(\"#yourIdMsg\").css(\"color\", \"red\");\r\n");
      out.write("			return false;				\r\n");
      out.write("		}\r\n");
      out.write("		\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			url: \"/member/idCheck\",\r\n");
      out.write("			method: \"get\",\r\n");
      out.write("			async: false,\r\n");
      out.write("			data: {\r\n");
      out.write("				mid : val\r\n");
      out.write("			},\r\n");
      out.write("			success: function(result) {\r\n");
      out.write("				if(result) {\r\n");
      out.write("					$(\"#yourIdMsg\").text(\"멋진 아이디네요!\");\r\n");
      out.write("					$(\"#yourIdMsg\").css(\"color\", \"#08a600\");\r\n");
      out.write("					idReturn = true;\r\n");
      out.write("				} else {	\r\n");
      out.write("					$(\"#yourIdMsg\").text(\"이미 사용중이거나 탈퇴한 아이디입니다.\");\r\n");
      out.write("					$(\"#yourIdMsg\").css(\"color\", \"red\");\r\n");
      out.write("					idReturn = false;\r\n");
      out.write("				}\r\n");
      out.write("			}\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		return idReturn;\r\n");
      out.write("  	}\r\n");
      out.write("  	\r\n");
      out.write("	function mbirthFunc() {\r\n");
      out.write("		var dtToday = new Date();\r\n");
      out.write("		\r\n");
      out.write("		var month = dtToday.getMonth() + 1;\r\n");
      out.write("		var day = dtToday.getDate();\r\n");
      out.write("		var year = dtToday.getFullYear();\r\n");
      out.write("		\r\n");
      out.write("		if(month < 10)\r\n");
      out.write("		    month = '0' + month.toString();\r\n");
      out.write("		if(day < 10)\r\n");
      out.write("		    day = '0' + day.toString();\r\n");
      out.write("		\r\n");
      out.write("		var maxDate = year + '-' + month + '-' + day;    \r\n");
      out.write("		$('#yourBirth').attr('max', maxDate);	 		\r\n");
      out.write("	}\r\n");
      out.write("  </script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("  <main>\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("\r\n");
      out.write("      <section class=\"section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("          <div class=\"row justify-content-center\" style=\"width:460px; margin:0 auto;\">\r\n");
      out.write("            <div class=\"d-flex flex-column align-items-center justify-content-center\">\r\n");
      out.write("\r\n");
      out.write("              <div class=\"d-flex justify-content-center py-4\">\r\n");
      out.write("                <a href=\"/\" class=\"logo d-flex align-items-center w-auto\">\r\n");
      out.write("                  <div style=\"font-weight:bold; font-size:50px; color:#23cb1a;\">EVER</div>\r\n");
      out.write("                </a>\r\n");
      out.write("              </div><!-- End Logo -->\r\n");
      out.write("\r\n");
      out.write("              <div class=\"card mb-3\" style=\"background:#f6f9ff !important; box-shadow:none;\">\r\n");
      out.write("\r\n");
      out.write("                <div class=\"card-body\" style=\"width:412px !important; margin: 0px 0 30px 0;\">\r\n");
      out.write("\r\n");
      out.write("                  <form id=\"registerForm\">\r\n");
      out.write("                    \r\n");
      out.write("                    <div class=\"input-group col-12\">\r\n");
      out.write("                      <label for=\"yourId\" class=\"form-label your-label\">아이디</label>\r\n");
      out.write("                      <div class=\"input-group\">\r\n");
      out.write("                        <input type=\"text\" name=\"mid\" class=\"form-control your-input\" \r\n");
      out.write("                              id=\"yourId\" aria-describedby=\"basic-addon2\" required>\r\n");
      out.write("                        <span class=\"input-group-text\" id=\"basic-addon2\">@naver.com</span>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div id=\"yourIdMsg\" class=\"mt-1 fs-13\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <label for=\"yourPassword\" class=\"form-label your-label\">비밀번호</label>\r\n");
      out.write("                      <input type=\"password\" name=\"mpassword\" class=\"form-control your-input\" id=\"yourPassword\" required>\r\n");
      out.write("                      <div id=\"yourPasswordMsg\" class=\"mt-1 fs-13\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <label for=\"yourRePassword\" class=\"form-label your-label\">비밀번호 재확인</label>\r\n");
      out.write("                      <input type=\"password\" class=\"form-control your-input\" id=\"yourRePassword\" required>\r\n");
      out.write("                      <div id=\"yourRePasswordMsg\" class=\"mt-1 fs-13\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <label for=\"yourName\" class=\"form-label your-label\">이름</label>\r\n");
      out.write("                      <input type=\"text\" name=\"mname\" class=\"form-control your-input\" id=\"yourName\" required>\r\n");
      out.write("                      <div id=\"yourNameMsg\" class=\"mt-1 fs-13\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <label for=\"yourNickname\" class=\"form-label your-label\">별명</label>\r\n");
      out.write("                      <input type=\"text\" name=\"mnickname\" class=\"form-control your-input\" id=\"yourNickname\" required>\r\n");
      out.write("                      <div id=\"yourNicknameMsg\" class=\"mt-1 fs-13\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                     <div class=\"col-12\">\r\n");
      out.write("                      <label for=\"yourBirth\" class=\"form-label your-label\">생년월일</label>\r\n");
      out.write("                      <div>\r\n");
      out.write("                        <input type=\"date\" name=\"mbirth\" class=\"form-control your-input\" id=\"yourBirth\" required>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      <div id=\"yourBirthMsg\" class=\"mt-1 fs-13\"></div>\r\n");
      out.write("                    </div> \r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <label for=\"yourGender\" class=\"form-label your-label\">성별</label>\r\n");
      out.write("                      <select id=\"yourGender\" name=\"mgender\" class=\"form-select your-input\" aria-label=\"Default select example\">\r\n");
      out.write("                        <option value=\"00\" selected>성별</option>\r\n");
      out.write("                        <option value=\"01\">남자</option>\r\n");
      out.write("                        <option value=\"02\">여자</option>\r\n");
      out.write("                        <option value=\"03\">선택 안함</option>\r\n");
      out.write("                      </select>\r\n");
      out.write("                      <div id=\"yourGenderMsg\" class=\"mt-1 fs-13\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <label for=\"yourEmail\" class=\"form-label your-label\">본인 확인 이메일</label>\r\n");
      out.write("                      <input type=\"text\" name=\"memail\" class=\"form-control your-input\" \r\n");
      out.write("                             placeholder=\"선택입력\" id=\"yourEmail\" required>\r\n");
      out.write("                      <div id=\"yourEmailMsg\" class=\"mt-1 fs-13\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"col-12\">\r\n");
      out.write("                      <label for=\"yourPhone\" class=\"form-label your-label\">휴대전화</label>\r\n");
      out.write("                      \r\n");
      out.write("                      <div class=\"row g-2\">\r\n");
      out.write("	                      <div class=\"col-8\">\r\n");
      out.write("	                        <input type=\"text\" name=\"mphone\" class=\"form-control your-input\" \r\n");
      out.write("	                               placeholder=\"전화번호 입력\" id=\"yourPhone\" required>\r\n");
      out.write("	                      </div>\r\n");
      out.write("	                      <div id=\"phoneBtn\" class=\"col-4\" style=\"margin-right:0px;\">\r\n");
      out.write("	                        <div class=\"btn btn-primary your-input\">인증번호 받기</div>\r\n");
      out.write("	                      </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      \r\n");
      out.write("                      <div class=\"row g2 mt-2\">\r\n");
      out.write("                      	<div class=\"col-12\">\r\n");
      out.write("                      	<input type=\"text\" class=\"form-control your-input\" \r\n");
      out.write("                               placeholder=\"인증번호 입력하세요\" id=\"yourPhoneConfirm\" disabled=\"disabled\" required>\r\n");
      out.write("                        </div>\r\n");
      out.write("                      </div>\r\n");
      out.write("                      \r\n");
      out.write("                      <div id=\"yourPhoneMsg\" class=\"mt-1 fs-13\"></div>\r\n");
      out.write("                      <div id=\"yourPhoneConfirmMsg\" class=\"mt-1 fs-13\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                               \r\n");
      out.write("                    <div class=\"col-12 mt-4\">\r\n");
      out.write("                      <div id=\"btn-submit\" class=\"btn btn-primary w-100 btn-submit\">가입하기</div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  </form>\r\n");
      out.write("\r\n");
      out.write("                </div>\r\n");
      out.write("              </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div class=\"d-flex justify-content-center credits\">\r\n");
      out.write("          Designed by <a href=\"https://bootstrapmade.com/\">BootstrapMade</a>\r\n");
      out.write("        </div>\r\n");
      out.write("      </section>\r\n");
      out.write("\r\n");
      out.write("    </div>\r\n");
      out.write("  </main><!-- End #main -->\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#\" class=\"back-to-top d-flex align-items-center justify-content-center\"><i class=\"bi bi-arrow-up-short\"></i></a>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
