/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-02-20 07:51:33 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SpringWeb/sts_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ever/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1642396012685L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("  <meta charset=\"utf-8\">\r\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\r\n");
      out.write("\r\n");
      out.write("  <title>Dashboard - NiceAdmin Bootstrap Template</title>\r\n");
      out.write("  <meta content=\"\" name=\"description\">\r\n");
      out.write("  <meta content=\"\" name=\"keywords\">\r\n");
      out.write("\r\n");
      out.write("  <!-- =======================================================\r\n");
      out.write("  * Template Name: NiceAdmin - v2.2.1\r\n");
      out.write("  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/\r\n");
      out.write("  * Author: BootstrapMade.com\r\n");
      out.write("  * License: https://bootstrapmade.com/license/\r\n");
      out.write("  ======================================================== -->\r\n");
      out.write("  <script src=\"http://code.jquery.com/jquery-latest.min.js\"></script>\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<main id=\"main\" class=\"main\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"pagetitle\">\r\n");
      out.write("      <h1>Dashboard</h1>\r\n");
      out.write("      <nav>\r\n");
      out.write("        <ol class=\"breadcrumb\">\r\n");
      out.write("          <li class=\"breadcrumb-item\"><a href=\"index.html\">Home</a></li>\r\n");
      out.write("          <li class=\"breadcrumb-item active\">Dashboard</li>\r\n");
      out.write("        </ol>\r\n");
      out.write("      </nav>\r\n");
      out.write("    </div><!-- End Page Title -->\r\n");
      out.write("\r\n");
      out.write("    <section class=\"section dashboard\">\r\n");
      out.write("		  <div class=\"row\">\r\n");
      out.write("	          <!-- News & Updates Traffic -->\r\n");
      out.write("	          <div class=\"col-12 col-lg-6\">\r\n");
      out.write("	            <div class=\"filter\">\r\n");
      out.write("	              <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>\r\n");
      out.write("	              <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">\r\n");
      out.write("	                <li class=\"dropdown-header text-start\">\r\n");
      out.write("	                  <h6>Filter</h6>\r\n");
      out.write("	                </li>\r\n");
      out.write("	\r\n");
      out.write("	                <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>\r\n");
      out.write("	                <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>\r\n");
      out.write("	                <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>\r\n");
      out.write("	              </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	\r\n");
      out.write("	            <div class=\"card-body pb-4\">\r\n");
      out.write("	              <h5 class=\"card-title\">News &amp; Updates <span>| Today</span></h5>\r\n");
      out.write("	\r\n");
      out.write("	              <div class=\"news\">\r\n");
      out.write("	                <div class=\"post-item clearfix\">\r\n");
      out.write("	                  <img src=\"assets/img/news-1.jpg\" alt=\"\">\r\n");
      out.write("	                  <h4><a href=\"#\">Nihil blanditiis at in nihil autem</a></h4>\r\n");
      out.write("	                  <p>Sit recusandae non aspernatur laboriosam. Quia enim eligendi sed ut harum...</p>\r\n");
      out.write("	                </div>\r\n");
      out.write("	\r\n");
      out.write("	                <div class=\"post-item clearfix\">\r\n");
      out.write("	                  <img src=\"assets/img/news-2.jpg\" alt=\"\">\r\n");
      out.write("	                  <h4><a href=\"#\">Quidem autem et impedit</a></h4>\r\n");
      out.write("	                  <p>Illo nemo neque maiores vitae officiis cum eum turos elan dries werona nande...</p>\r\n");
      out.write("	                </div>\r\n");
      out.write("	\r\n");
      out.write("	                <div class=\"post-item clearfix\">\r\n");
      out.write("	                  <img src=\"assets/img/news-3.jpg\" alt=\"\">\r\n");
      out.write("	                  <h4><a href=\"#\">Id quia et et ut maxime similique occaecati ut</a></h4>\r\n");
      out.write("	                  <p>Fugiat voluptas vero eaque accusantium eos. Consequuntur sed ipsam et totam...</p>\r\n");
      out.write("	                </div>\r\n");
      out.write("	\r\n");
      out.write("	                <div class=\"post-item clearfix\">\r\n");
      out.write("	                  <img src=\"assets/img/news-4.jpg\" alt=\"\">\r\n");
      out.write("	                  <h4><a href=\"#\">Laborum corporis quo dara net para</a></h4>\r\n");
      out.write("	                  <p>Qui enim quia optio. Eligendi aut asperiores enim repellendusvel rerum cuder...</p>\r\n");
      out.write("	                </div>\r\n");
      out.write("	\r\n");
      out.write("	                <div class=\"post-item clearfix\">\r\n");
      out.write("	                  <img src=\"assets/img/news-5.jpg\" alt=\"\">\r\n");
      out.write("	                  <h4><a href=\"#\">Et dolores corrupti quae illo quod dolor</a></h4>\r\n");
      out.write("	                  <p>Odit ut eveniet modi reiciendis. Atque cupiditate libero beatae dignissimos eius...</p>\r\n");
      out.write("	                </div>\r\n");
      out.write("	\r\n");
      out.write("	              </div><!-- End sidebar recent posts-->\r\n");
      out.write("	\r\n");
      out.write("	            </div>\r\n");
      out.write("	          </div><!-- End News & Updates -->\r\n");
      out.write("\r\n");
      out.write("	          <!-- News & Updates Traffic -->\r\n");
      out.write("	          <div class=\"col-12 col-lg-6\">\r\n");
      out.write("	            <div class=\"filter\">\r\n");
      out.write("	              <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>\r\n");
      out.write("	              <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">\r\n");
      out.write("	                <li class=\"dropdown-header text-start\">\r\n");
      out.write("	                  <h6>Filter</h6>\r\n");
      out.write("	                </li>\r\n");
      out.write("	\r\n");
      out.write("	                <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>\r\n");
      out.write("	                <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>\r\n");
      out.write("	                <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>\r\n");
      out.write("	              </ul>\r\n");
      out.write("	            </div>\r\n");
      out.write("	\r\n");
      out.write("	            <div class=\"card-body pb-4\">\r\n");
      out.write("	              <h5 class=\"card-title\">News &amp; Updates <span>| Today</span></h5>\r\n");
      out.write("	\r\n");
      out.write("	              <div class=\"news\">\r\n");
      out.write("	                <div class=\"post-item clearfix\">\r\n");
      out.write("	                  <img src=\"assets/img/news-1.jpg\" alt=\"\">\r\n");
      out.write("	                  <h4><a href=\"#\">Nihil blanditiis at in nihil autem</a></h4>\r\n");
      out.write("	                  <p>Sit recusandae non aspernatur laboriosam. Quia enim eligendi sed ut harum...</p>\r\n");
      out.write("	                </div>\r\n");
      out.write("	\r\n");
      out.write("	                <div class=\"post-item clearfix\">\r\n");
      out.write("	                  <img src=\"assets/img/news-2.jpg\" alt=\"\">\r\n");
      out.write("	                  <h4><a href=\"#\">Quidem autem et impedit</a></h4>\r\n");
      out.write("	                  <p>Illo nemo neque maiores vitae officiis cum eum turos elan dries werona nande...</p>\r\n");
      out.write("	                </div>\r\n");
      out.write("	\r\n");
      out.write("	                <div class=\"post-item clearfix\">\r\n");
      out.write("	                  <img src=\"assets/img/news-3.jpg\" alt=\"\">\r\n");
      out.write("	                  <h4><a href=\"#\">Id quia et et ut maxime similique occaecati ut</a></h4>\r\n");
      out.write("	                  <p>Fugiat voluptas vero eaque accusantium eos. Consequuntur sed ipsam et totam...</p>\r\n");
      out.write("	                </div>\r\n");
      out.write("	\r\n");
      out.write("	                <div class=\"post-item clearfix\">\r\n");
      out.write("	                  <img src=\"assets/img/news-4.jpg\" alt=\"\">\r\n");
      out.write("	                  <h4><a href=\"#\">Laborum corporis quo dara net para</a></h4>\r\n");
      out.write("	                  <p>Qui enim quia optio. Eligendi aut asperiores enim repellendusvel rerum cuder...</p>\r\n");
      out.write("	                </div>\r\n");
      out.write("	\r\n");
      out.write("	                <div class=\"post-item clearfix\">\r\n");
      out.write("	                  <img src=\"assets/img/news-5.jpg\" alt=\"\">\r\n");
      out.write("	                  <h4><a href=\"#\">Et dolores corrupti quae illo quod dolor</a></h4>\r\n");
      out.write("	                  <p>Odit ut eveniet modi reiciendis. Atque cupiditate libero beatae dignissimos eius...</p>\r\n");
      out.write("	                </div>\r\n");
      out.write("	\r\n");
      out.write("	              </div><!-- End sidebar recent posts-->\r\n");
      out.write("	           </div>\r\n");
      out.write("\r\n");
      out.write("            </div>\r\n");
      out.write("          </div><!-- End News & Updates -->\r\n");
      out.write("\r\n");
      out.write("    </section>\r\n");
      out.write("\r\n");
      out.write("</main><!-- End #main -->\r\n");
      out.write("\r\n");
      if (_jspx_meth_c_005fimport_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(26,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("/header");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(27,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("/sidebar");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f2 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f2_reused = false;
    try {
      _jspx_th_c_005fimport_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f2.setParent(null);
      // /WEB-INF/views/home.jsp(156,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f2.setUrl("/footer");
      int[] _jspx_push_body_count_c_005fimport_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f2 = _jspx_th_c_005fimport_005f2.doStartTag();
        if (_jspx_th_c_005fimport_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fnobody.reuse(_jspx_th_c_005fimport_005f2);
      _jspx_th_c_005fimport_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f2_reused);
    }
    return false;
  }
}
