/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.5.73
 * Generated at: 2022-01-26 15:17:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class home_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("jar:file:/C:/SpringProjects/sts01_work/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ever/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1643011921376L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html lang=\"ko\">\n");
      out.write("\n");
      out.write("<head>\n");
      out.write("  <meta charset=\"utf-8\">\n");
      out.write("  <meta content=\"width=device-width, initial-scale=1.0\" name=\"viewport\">\n");
      out.write("\n");
      out.write("  <title>Dashboard - NiceAdmin Bootstrap Template</title>\n");
      out.write("  <meta content=\"\" name=\"description\">\n");
      out.write("  <meta content=\"\" name=\"keywords\">\n");
      out.write("\n");
      out.write("  <!-- =======================================================\n");
      out.write("  * Template Name: NiceAdmin - v2.2.1\n");
      out.write("  * Template URL: https://bootstrapmade.com/nice-admin-bootstrap-admin-html-template/\n");
      out.write("  * Author: BootstrapMade.com\n");
      out.write("  * License: https://bootstrapmade.com/license/\n");
      out.write("  ======================================================== -->\n");
      out.write("</head>\n");
      out.write("\n");
      out.write("<body>\n");
      out.write("\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/header", out, false);
      out.write("\n");
      out.write("  \n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/sidebar", out, false);
      out.write("\n");
      out.write("\n");
      out.write("  <main id=\"main\" class=\"main\">\n");
      out.write("\n");
      out.write("    <div class=\"pagetitle\">\n");
      out.write("      <h1>Dashboard</h1>\n");
      out.write("      <nav>\n");
      out.write("        <ol class=\"breadcrumb\">\n");
      out.write("          <li class=\"breadcrumb-item\"><a href=\"index.html\">Home</a></li>\n");
      out.write("          <li class=\"breadcrumb-item active\">Dashboard</li>\n");
      out.write("        </ol>\n");
      out.write("      </nav>\n");
      out.write("    </div><!-- End Page Title -->\n");
      out.write("\n");
      out.write("    <section class=\"section dashboard\">\n");
      out.write("      <div class=\"row\">\n");
      out.write("\n");
      out.write("        <!-- Left side columns -->\n");
      out.write("        <div class=\"col-lg-8\">\n");
      out.write("          <div class=\"row\">\n");
      out.write("\n");
      out.write("            <!-- Sales Card -->\n");
      out.write("            <div class=\"col-xxl-4 col-md-6\">\n");
      out.write("              <div class=\"card info-card sales-card\">\n");
      out.write("\n");
      out.write("                <div class=\"filter\">\n");
      out.write("                  <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>\n");
      out.write("                  <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">\n");
      out.write("                    <li class=\"dropdown-header text-start\">\n");
      out.write("                      <h6>Filter</h6>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                  <h5 class=\"card-title\">Sales <span>| Today</span></h5>\n");
      out.write("\n");
      out.write("                  <div class=\"d-flex align-items-center\">\n");
      out.write("                    <div class=\"card-icon rounded-circle d-flex align-items-center justify-content-center\">\n");
      out.write("                      <i class=\"bi bi-cart\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"ps-3\">\n");
      out.write("                      <h6>145</h6>\n");
      out.write("                      <span class=\"text-success small pt-1 fw-bold\">12%</span> <span class=\"text-muted small pt-2 ps-1\">increase</span>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("            </div><!-- End Sales Card -->\n");
      out.write("\n");
      out.write("            <!-- Revenue Card -->\n");
      out.write("            <div class=\"col-xxl-4 col-md-6\">\n");
      out.write("              <div class=\"card info-card revenue-card\">\n");
      out.write("\n");
      out.write("                <div class=\"filter\">\n");
      out.write("                  <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>\n");
      out.write("                  <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">\n");
      out.write("                    <li class=\"dropdown-header text-start\">\n");
      out.write("                      <h6>Filter</h6>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                  <h5 class=\"card-title\">Revenue <span>| This Month</span></h5>\n");
      out.write("\n");
      out.write("                  <div class=\"d-flex align-items-center\">\n");
      out.write("                    <div class=\"card-icon rounded-circle d-flex align-items-center justify-content-center\">\n");
      out.write("                      <i class=\"bi bi-currency-dollar\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"ps-3\">\n");
      out.write("                      <h6>$3,264</h6>\n");
      out.write("                      <span class=\"text-success small pt-1 fw-bold\">8%</span> <span class=\"text-muted small pt-2 ps-1\">increase</span>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("            </div><!-- End Revenue Card -->\n");
      out.write("\n");
      out.write("            <!-- Customers Card -->\n");
      out.write("            <div class=\"col-xxl-4 col-xl-12\">\n");
      out.write("\n");
      out.write("              <div class=\"card info-card customers-card\">\n");
      out.write("\n");
      out.write("                <div class=\"filter\">\n");
      out.write("                  <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>\n");
      out.write("                  <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">\n");
      out.write("                    <li class=\"dropdown-header text-start\">\n");
      out.write("                      <h6>Filter</h6>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                  <h5 class=\"card-title\">Customers <span>| This Year</span></h5>\n");
      out.write("\n");
      out.write("                  <div class=\"d-flex align-items-center\">\n");
      out.write("                    <div class=\"card-icon rounded-circle d-flex align-items-center justify-content-center\">\n");
      out.write("                      <i class=\"bi bi-people\"></i>\n");
      out.write("                    </div>\n");
      out.write("                    <div class=\"ps-3\">\n");
      out.write("                      <h6>1244</h6>\n");
      out.write("                      <span class=\"text-danger small pt-1 fw-bold\">12%</span> <span class=\"text-muted small pt-2 ps-1\">decrease</span>\n");
      out.write("\n");
      out.write("                    </div>\n");
      out.write("                  </div>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("            </div><!-- End Customers Card -->\n");
      out.write("\n");
      out.write("            <!-- Reports -->\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("              <div class=\"card\">\n");
      out.write("\n");
      out.write("                <div class=\"filter\">\n");
      out.write("                  <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>\n");
      out.write("                  <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">\n");
      out.write("                    <li class=\"dropdown-header text-start\">\n");
      out.write("                      <h6>Filter</h6>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                  <h5 class=\"card-title\">Reports <span>/Today</span></h5>\n");
      out.write("\n");
      out.write("                  <!-- Line Chart -->\n");
      out.write("                  <div id=\"reportsChart\"></div>\n");
      out.write("\n");
      out.write("                  <script>\n");
      out.write("                    document.addEventListener(\"DOMContentLoaded\", () => {\n");
      out.write("                      new ApexCharts(document.querySelector(\"#reportsChart\"), {\n");
      out.write("                        series: [{\n");
      out.write("                          name: 'Sales',\n");
      out.write("                          data: [31, 40, 28, 51, 42, 82, 56],\n");
      out.write("                        }, {\n");
      out.write("                          name: 'Revenue',\n");
      out.write("                          data: [11, 32, 45, 32, 34, 52, 41]\n");
      out.write("                        }, {\n");
      out.write("                          name: 'Customers',\n");
      out.write("                          data: [15, 11, 32, 18, 9, 24, 11]\n");
      out.write("                        }],\n");
      out.write("                        chart: {\n");
      out.write("                          height: 350,\n");
      out.write("                          type: 'area',\n");
      out.write("                          toolbar: {\n");
      out.write("                            show: false\n");
      out.write("                          },\n");
      out.write("                        },\n");
      out.write("                        markers: {\n");
      out.write("                          size: 4\n");
      out.write("                        },\n");
      out.write("                        colors: ['#4154f1', '#2eca6a', '#ff771d'],\n");
      out.write("                        fill: {\n");
      out.write("                          type: \"gradient\",\n");
      out.write("                          gradient: {\n");
      out.write("                            shadeIntensity: 1,\n");
      out.write("                            opacityFrom: 0.3,\n");
      out.write("                            opacityTo: 0.4,\n");
      out.write("                            stops: [0, 90, 100]\n");
      out.write("                          }\n");
      out.write("                        },\n");
      out.write("                        dataLabels: {\n");
      out.write("                          enabled: false\n");
      out.write("                        },\n");
      out.write("                        stroke: {\n");
      out.write("                          curve: 'smooth',\n");
      out.write("                          width: 2\n");
      out.write("                        },\n");
      out.write("                        xaxis: {\n");
      out.write("                          type: 'datetime',\n");
      out.write("                          categories: [\"2018-09-19T00:00:00.000Z\", \"2018-09-19T01:30:00.000Z\", \"2018-09-19T02:30:00.000Z\", \"2018-09-19T03:30:00.000Z\", \"2018-09-19T04:30:00.000Z\", \"2018-09-19T05:30:00.000Z\", \"2018-09-19T06:30:00.000Z\"]\n");
      out.write("                        },\n");
      out.write("                        tooltip: {\n");
      out.write("                          x: {\n");
      out.write("                            format: 'dd/MM/yy HH:mm'\n");
      out.write("                          },\n");
      out.write("                        }\n");
      out.write("                      }).render();\n");
      out.write("                    });\n");
      out.write("                  </script>\n");
      out.write("                  <!-- End Line Chart -->\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("            </div><!-- End Reports -->\n");
      out.write("\n");
      out.write("            <!-- Recent Sales -->\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("              <div class=\"card recent-sales\">\n");
      out.write("\n");
      out.write("                <div class=\"filter\">\n");
      out.write("                  <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>\n");
      out.write("                  <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">\n");
      out.write("                    <li class=\"dropdown-header text-start\">\n");
      out.write("                      <h6>Filter</h6>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"card-body\">\n");
      out.write("                  <h5 class=\"card-title\">Recent Sales <span>| Today</span></h5>\n");
      out.write("\n");
      out.write("                  <table class=\"table table-borderless datatable\">\n");
      out.write("                    <thead>\n");
      out.write("                      <tr>\n");
      out.write("                        <th scope=\"col\">#</th>\n");
      out.write("                        <th scope=\"col\">Customer</th>\n");
      out.write("                        <th scope=\"col\">Product</th>\n");
      out.write("                        <th scope=\"col\">Price</th>\n");
      out.write("                        <th scope=\"col\">Status</th>\n");
      out.write("                      </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                      <tr>\n");
      out.write("                        <th scope=\"row\"><a href=\"#\">#2457</a></th>\n");
      out.write("                        <td>Brandon Jacob</td>\n");
      out.write("                        <td><a href=\"#\" class=\"text-primary\">At praesentium minu</a></td>\n");
      out.write("                        <td>$64</td>\n");
      out.write("                        <td><span class=\"badge bg-success\">Approved</span></td>\n");
      out.write("                      </tr>\n");
      out.write("                      <tr>\n");
      out.write("                        <th scope=\"row\"><a href=\"#\">#2147</a></th>\n");
      out.write("                        <td>Bridie Kessler</td>\n");
      out.write("                        <td><a href=\"#\" class=\"text-primary\">Blanditiis dolor omnis similique</a></td>\n");
      out.write("                        <td>$47</td>\n");
      out.write("                        <td><span class=\"badge bg-warning\">Pending</span></td>\n");
      out.write("                      </tr>\n");
      out.write("                      <tr>\n");
      out.write("                        <th scope=\"row\"><a href=\"#\">#2049</a></th>\n");
      out.write("                        <td>Ashleigh Langosh</td>\n");
      out.write("                        <td><a href=\"#\" class=\"text-primary\">At recusandae consectetur</a></td>\n");
      out.write("                        <td>$147</td>\n");
      out.write("                        <td><span class=\"badge bg-success\">Approved</span></td>\n");
      out.write("                      </tr>\n");
      out.write("                      <tr>\n");
      out.write("                        <th scope=\"row\"><a href=\"#\">#2644</a></th>\n");
      out.write("                        <td>Angus Grady</td>\n");
      out.write("                        <td><a href=\"#\" class=\"text-primar\">Ut voluptatem id earum et</a></td>\n");
      out.write("                        <td>$67</td>\n");
      out.write("                        <td><span class=\"badge bg-danger\">Rejected</span></td>\n");
      out.write("                      </tr>\n");
      out.write("                      <tr>\n");
      out.write("                        <th scope=\"row\"><a href=\"#\">#2644</a></th>\n");
      out.write("                        <td>Raheem Lehner</td>\n");
      out.write("                        <td><a href=\"#\" class=\"text-primary\">Sunt similique distinctio</a></td>\n");
      out.write("                        <td>$165</td>\n");
      out.write("                        <td><span class=\"badge bg-success\">Approved</span></td>\n");
      out.write("                      </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                  </table>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("            </div><!-- End Recent Sales -->\n");
      out.write("\n");
      out.write("            <!-- Top Selling -->\n");
      out.write("            <div class=\"col-12\">\n");
      out.write("              <div class=\"card top-selling\">\n");
      out.write("\n");
      out.write("                <div class=\"filter\">\n");
      out.write("                  <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>\n");
      out.write("                  <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">\n");
      out.write("                    <li class=\"dropdown-header text-start\">\n");
      out.write("                      <h6>Filter</h6>\n");
      out.write("                    </li>\n");
      out.write("\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>\n");
      out.write("                    <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>\n");
      out.write("                  </ul>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"card-body pb-0\">\n");
      out.write("                  <h5 class=\"card-title\">Top Selling <span>| Today</span></h5>\n");
      out.write("\n");
      out.write("                  <table class=\"table table-borderless\">\n");
      out.write("                    <thead>\n");
      out.write("                      <tr>\n");
      out.write("                        <th scope=\"col\">Preview</th>\n");
      out.write("                        <th scope=\"col\">Product</th>\n");
      out.write("                        <th scope=\"col\">Price</th>\n");
      out.write("                        <th scope=\"col\">Sold</th>\n");
      out.write("                        <th scope=\"col\">Revenue</th>\n");
      out.write("                      </tr>\n");
      out.write("                    </thead>\n");
      out.write("                    <tbody>\n");
      out.write("                      <tr>\n");
      out.write("                        <th scope=\"row\"><a href=\"#\"><img src=\"assets/img/product-1.jpg\" alt=\"\"></a></th>\n");
      out.write("                        <td><a href=\"#\" class=\"text-primary fw-bold\">Ut inventore ipsa voluptas nulla</a></td>\n");
      out.write("                        <td>$64</td>\n");
      out.write("                        <td class=\"fw-bold\">124</td>\n");
      out.write("                        <td>$5,828</td>\n");
      out.write("                      </tr>\n");
      out.write("                      <tr>\n");
      out.write("                        <th scope=\"row\"><a href=\"#\"><img src=\"assets/img/product-2.jpg\" alt=\"\"></a></th>\n");
      out.write("                        <td><a href=\"#\" class=\"text-primary fw-bold\">Exercitationem similique doloremque</a></td>\n");
      out.write("                        <td>$46</td>\n");
      out.write("                        <td class=\"fw-bold\">98</td>\n");
      out.write("                        <td>$4,508</td>\n");
      out.write("                      </tr>\n");
      out.write("                      <tr>\n");
      out.write("                        <th scope=\"row\"><a href=\"#\"><img src=\"assets/img/product-3.jpg\" alt=\"\"></a></th>\n");
      out.write("                        <td><a href=\"#\" class=\"text-primary fw-bold\">Doloribus nisi exercitationem</a></td>\n");
      out.write("                        <td>$59</td>\n");
      out.write("                        <td class=\"fw-bold\">74</td>\n");
      out.write("                        <td>$4,366</td>\n");
      out.write("                      </tr>\n");
      out.write("                      <tr>\n");
      out.write("                        <th scope=\"row\"><a href=\"#\"><img src=\"assets/img/product-4.jpg\" alt=\"\"></a></th>\n");
      out.write("                        <td><a href=\"#\" class=\"text-primary fw-bold\">Officiis quaerat sint rerum error</a></td>\n");
      out.write("                        <td>$32</td>\n");
      out.write("                        <td class=\"fw-bold\">63</td>\n");
      out.write("                        <td>$2,016</td>\n");
      out.write("                      </tr>\n");
      out.write("                      <tr>\n");
      out.write("                        <th scope=\"row\"><a href=\"#\"><img src=\"assets/img/product-5.jpg\" alt=\"\"></a></th>\n");
      out.write("                        <td><a href=\"#\" class=\"text-primary fw-bold\">Sit unde debitis delectus repellendus</a></td>\n");
      out.write("                        <td>$79</td>\n");
      out.write("                        <td class=\"fw-bold\">41</td>\n");
      out.write("                        <td>$3,239</td>\n");
      out.write("                      </tr>\n");
      out.write("                    </tbody>\n");
      out.write("                  </table>\n");
      out.write("\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("            </div><!-- End Top Selling -->\n");
      out.write("\n");
      out.write("          </div>\n");
      out.write("        </div><!-- End Left side columns -->\n");
      out.write("\n");
      out.write("        <!-- Right side columns -->\n");
      out.write("        <div class=\"col-lg-4\">\n");
      out.write("\n");
      out.write("          <!-- Recent Activity -->\n");
      out.write("          <div class=\"card\">\n");
      out.write("            <div class=\"filter\">\n");
      out.write("              <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>\n");
      out.write("              <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">\n");
      out.write("                <li class=\"dropdown-header text-start\">\n");
      out.write("                  <h6>Filter</h6>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"card-body\">\n");
      out.write("              <h5 class=\"card-title\">Recent Activity <span>| Today</span></h5>\n");
      out.write("\n");
      out.write("              <div class=\"activity\">\n");
      out.write("\n");
      out.write("                <div class=\"activity-item d-flex\">\n");
      out.write("                  <div class=\"activite-label\">32 min</div>\n");
      out.write("                  <i class='bi bi-circle-fill activity-badge text-success align-self-start'></i>\n");
      out.write("                  <div class=\"activity-content\">\n");
      out.write("                    Quia quae rerum <a href=\"#\" class=\"fw-bold text-dark\">explicabo officiis</a> beatae\n");
      out.write("                  </div>\n");
      out.write("                </div><!-- End activity item-->\n");
      out.write("\n");
      out.write("                <div class=\"activity-item d-flex\">\n");
      out.write("                  <div class=\"activite-label\">56 min</div>\n");
      out.write("                  <i class='bi bi-circle-fill activity-badge text-danger align-self-start'></i>\n");
      out.write("                  <div class=\"activity-content\">\n");
      out.write("                    Voluptatem blanditiis blanditiis eveniet\n");
      out.write("                  </div>\n");
      out.write("                </div><!-- End activity item-->\n");
      out.write("\n");
      out.write("                <div class=\"activity-item d-flex\">\n");
      out.write("                  <div class=\"activite-label\">2 hrs</div>\n");
      out.write("                  <i class='bi bi-circle-fill activity-badge text-primary align-self-start'></i>\n");
      out.write("                  <div class=\"activity-content\">\n");
      out.write("                    Voluptates corrupti molestias voluptatem\n");
      out.write("                  </div>\n");
      out.write("                </div><!-- End activity item-->\n");
      out.write("\n");
      out.write("                <div class=\"activity-item d-flex\">\n");
      out.write("                  <div class=\"activite-label\">1 day</div>\n");
      out.write("                  <i class='bi bi-circle-fill activity-badge text-info align-self-start'></i>\n");
      out.write("                  <div class=\"activity-content\">\n");
      out.write("                    Tempore autem saepe <a href=\"#\" class=\"fw-bold text-dark\">occaecati voluptatem</a> tempore\n");
      out.write("                  </div>\n");
      out.write("                </div><!-- End activity item-->\n");
      out.write("\n");
      out.write("                <div class=\"activity-item d-flex\">\n");
      out.write("                  <div class=\"activite-label\">2 days</div>\n");
      out.write("                  <i class='bi bi-circle-fill activity-badge text-warning align-self-start'></i>\n");
      out.write("                  <div class=\"activity-content\">\n");
      out.write("                    Est sit eum reiciendis exercitationem\n");
      out.write("                  </div>\n");
      out.write("                </div><!-- End activity item-->\n");
      out.write("\n");
      out.write("                <div class=\"activity-item d-flex\">\n");
      out.write("                  <div class=\"activite-label\">4 weeks</div>\n");
      out.write("                  <i class='bi bi-circle-fill activity-badge text-muted align-self-start'></i>\n");
      out.write("                  <div class=\"activity-content\">\n");
      out.write("                    Dicta dolorem harum nulla eius. Ut quidem quidem sit quas\n");
      out.write("                  </div>\n");
      out.write("                </div><!-- End activity item-->\n");
      out.write("\n");
      out.write("              </div>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div><!-- End Recent Activity -->\n");
      out.write("\n");
      out.write("          <!-- Budget Report -->\n");
      out.write("          <div class=\"card\">\n");
      out.write("            <div class=\"filter\">\n");
      out.write("              <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>\n");
      out.write("              <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">\n");
      out.write("                <li class=\"dropdown-header text-start\">\n");
      out.write("                  <h6>Filter</h6>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"card-body pb-0\">\n");
      out.write("              <h5 class=\"card-title\">Budget Report <span>| This Month</span></h5>\n");
      out.write("\n");
      out.write("              <div id=\"budgetChart\" style=\"min-height: 400px;\" class=\"echart\"></div>\n");
      out.write("\n");
      out.write("              <script>\n");
      out.write("                document.addEventListener(\"DOMContentLoaded\", () => {\n");
      out.write("                  var budgetChart = echarts.init(document.querySelector(\"#budgetChart\")).setOption({\n");
      out.write("                    legend: {\n");
      out.write("                      data: ['Allocated Budget', 'Actual Spending']\n");
      out.write("                    },\n");
      out.write("                    radar: {\n");
      out.write("                      // shape: 'circle',\n");
      out.write("                      indicator: [{\n");
      out.write("                          name: 'Sales',\n");
      out.write("                          max: 6500\n");
      out.write("                        },\n");
      out.write("                        {\n");
      out.write("                          name: 'Administration',\n");
      out.write("                          max: 16000\n");
      out.write("                        },\n");
      out.write("                        {\n");
      out.write("                          name: 'Information Technology',\n");
      out.write("                          max: 30000\n");
      out.write("                        },\n");
      out.write("                        {\n");
      out.write("                          name: 'Customer Support',\n");
      out.write("                          max: 38000\n");
      out.write("                        },\n");
      out.write("                        {\n");
      out.write("                          name: 'Development',\n");
      out.write("                          max: 52000\n");
      out.write("                        },\n");
      out.write("                        {\n");
      out.write("                          name: 'Marketing',\n");
      out.write("                          max: 25000\n");
      out.write("                        }\n");
      out.write("                      ]\n");
      out.write("                    },\n");
      out.write("                    series: [{\n");
      out.write("                      name: 'Budget vs spending',\n");
      out.write("                      type: 'radar',\n");
      out.write("                      data: [{\n");
      out.write("                          value: [4200, 3000, 20000, 35000, 50000, 18000],\n");
      out.write("                          name: 'Allocated Budget'\n");
      out.write("                        },\n");
      out.write("                        {\n");
      out.write("                          value: [5000, 14000, 28000, 26000, 42000, 21000],\n");
      out.write("                          name: 'Actual Spending'\n");
      out.write("                        }\n");
      out.write("                      ]\n");
      out.write("                    }]\n");
      out.write("                  });\n");
      out.write("                });\n");
      out.write("              </script>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div><!-- End Budget Report -->\n");
      out.write("\n");
      out.write("          <!-- Website Traffic -->\n");
      out.write("          <div class=\"card\">\n");
      out.write("            <div class=\"filter\">\n");
      out.write("              <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>\n");
      out.write("              <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">\n");
      out.write("                <li class=\"dropdown-header text-start\">\n");
      out.write("                  <h6>Filter</h6>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"card-body pb-0\">\n");
      out.write("              <h5 class=\"card-title\">Website Traffic <span>| Today</span></h5>\n");
      out.write("\n");
      out.write("              <div id=\"trafficChart\" style=\"min-height: 400px;\" class=\"echart\"></div>\n");
      out.write("\n");
      out.write("              <script>\n");
      out.write("                document.addEventListener(\"DOMContentLoaded\", () => {\n");
      out.write("                  echarts.init(document.querySelector(\"#trafficChart\")).setOption({\n");
      out.write("                    tooltip: {\n");
      out.write("                      trigger: 'item'\n");
      out.write("                    },\n");
      out.write("                    legend: {\n");
      out.write("                      top: '5%',\n");
      out.write("                      left: 'center'\n");
      out.write("                    },\n");
      out.write("                    series: [{\n");
      out.write("                      name: 'Access From',\n");
      out.write("                      type: 'pie',\n");
      out.write("                      radius: ['40%', '70%'],\n");
      out.write("                      avoidLabelOverlap: false,\n");
      out.write("                      label: {\n");
      out.write("                        show: false,\n");
      out.write("                        position: 'center'\n");
      out.write("                      },\n");
      out.write("                      emphasis: {\n");
      out.write("                        label: {\n");
      out.write("                          show: true,\n");
      out.write("                          fontSize: '18',\n");
      out.write("                          fontWeight: 'bold'\n");
      out.write("                        }\n");
      out.write("                      },\n");
      out.write("                      labelLine: {\n");
      out.write("                        show: false\n");
      out.write("                      },\n");
      out.write("                      data: [{\n");
      out.write("                          value: 1048,\n");
      out.write("                          name: 'Search Engine'\n");
      out.write("                        },\n");
      out.write("                        {\n");
      out.write("                          value: 735,\n");
      out.write("                          name: 'Direct'\n");
      out.write("                        },\n");
      out.write("                        {\n");
      out.write("                          value: 580,\n");
      out.write("                          name: 'Email'\n");
      out.write("                        },\n");
      out.write("                        {\n");
      out.write("                          value: 484,\n");
      out.write("                          name: 'Union Ads'\n");
      out.write("                        },\n");
      out.write("                        {\n");
      out.write("                          value: 300,\n");
      out.write("                          name: 'Video Ads'\n");
      out.write("                        }\n");
      out.write("                      ]\n");
      out.write("                    }]\n");
      out.write("                  });\n");
      out.write("                });\n");
      out.write("              </script>\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div><!-- End Website Traffic -->\n");
      out.write("\n");
      out.write("          <!-- News & Updates Traffic -->\n");
      out.write("          <div class=\"card\">\n");
      out.write("            <div class=\"filter\">\n");
      out.write("              <a class=\"icon\" href=\"#\" data-bs-toggle=\"dropdown\"><i class=\"bi bi-three-dots\"></i></a>\n");
      out.write("              <ul class=\"dropdown-menu dropdown-menu-end dropdown-menu-arrow\">\n");
      out.write("                <li class=\"dropdown-header text-start\">\n");
      out.write("                  <h6>Filter</h6>\n");
      out.write("                </li>\n");
      out.write("\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">Today</a></li>\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">This Month</a></li>\n");
      out.write("                <li><a class=\"dropdown-item\" href=\"#\">This Year</a></li>\n");
      out.write("              </ul>\n");
      out.write("            </div>\n");
      out.write("\n");
      out.write("            <div class=\"card-body pb-0\">\n");
      out.write("              <h5 class=\"card-title\">News &amp; Updates <span>| Today</span></h5>\n");
      out.write("\n");
      out.write("              <div class=\"news\">\n");
      out.write("                <div class=\"post-item clearfix\">\n");
      out.write("                  <img src=\"assets/img/news-1.jpg\" alt=\"\">\n");
      out.write("                  <h4><a href=\"#\">Nihil blanditiis at in nihil autem</a></h4>\n");
      out.write("                  <p>Sit recusandae non aspernatur laboriosam. Quia enim eligendi sed ut harum...</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"post-item clearfix\">\n");
      out.write("                  <img src=\"assets/img/news-2.jpg\" alt=\"\">\n");
      out.write("                  <h4><a href=\"#\">Quidem autem et impedit</a></h4>\n");
      out.write("                  <p>Illo nemo neque maiores vitae officiis cum eum turos elan dries werona nande...</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"post-item clearfix\">\n");
      out.write("                  <img src=\"assets/img/news-3.jpg\" alt=\"\">\n");
      out.write("                  <h4><a href=\"#\">Id quia et et ut maxime similique occaecati ut</a></h4>\n");
      out.write("                  <p>Fugiat voluptas vero eaque accusantium eos. Consequuntur sed ipsam et totam...</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"post-item clearfix\">\n");
      out.write("                  <img src=\"assets/img/news-4.jpg\" alt=\"\">\n");
      out.write("                  <h4><a href=\"#\">Laborum corporis quo dara net para</a></h4>\n");
      out.write("                  <p>Qui enim quia optio. Eligendi aut asperiores enim repellendusvel rerum cuder...</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("                <div class=\"post-item clearfix\">\n");
      out.write("                  <img src=\"assets/img/news-5.jpg\" alt=\"\">\n");
      out.write("                  <h4><a href=\"#\">Et dolores corrupti quae illo quod dolor</a></h4>\n");
      out.write("                  <p>Odit ut eveniet modi reiciendis. Atque cupiditate libero beatae dignissimos eius...</p>\n");
      out.write("                </div>\n");
      out.write("\n");
      out.write("              </div><!-- End sidebar recent posts-->\n");
      out.write("\n");
      out.write("            </div>\n");
      out.write("          </div><!-- End News & Updates -->\n");
      out.write("\n");
      out.write("        </div><!-- End Right side columns -->\n");
      out.write("\n");
      out.write("      </div>\n");
      out.write("    </section>\n");
      out.write("\n");
      out.write("  </main><!-- End #main -->\n");
      out.write("\n");
      out.write("  ");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer", out, false);
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("\n");
      out.write("</html>\n");
      out.write("\n");
      out.write("<!--  \n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("	<title>Home</title>\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("<h1>\n");
      out.write("	Hello world!  \n");
      out.write("</h1>\n");
      out.write("\n");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write('\n');
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\n");
      out.write("\n");
      out.write("<P>  The time on the server is ");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${serverTime}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(". </P>\n");
      out.write("</body>\n");
      out.write("</html>\n");
      out.write("-->");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f0_reused = false;
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/views/home.jsp(693,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member == null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("	<a href=\"/member/register\">회원가입</a>\n");
          out.write("	<a href=\"/member/login\">로그인</a>\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
      _jspx_th_c_005fif_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    boolean _jspx_th_c_005fif_005f1_reused = false;
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/views/home.jsp(697,0) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member != null}", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\n");
          out.write("	<p>");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${member.mid}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("님 환영합니다.</p>\n");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
      _jspx_th_c_005fif_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fif_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fif_005f1_reused);
    }
    return false;
  }
}
